version: "3.9"
services:
  app:
    build: .
    container_name: user-app1
    ports:
      - "3000:3000"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.2
  app2:
    build: .
    container_name: user-app2
    ports:
      - "3001:3000"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
